### ISSUE TITLE
Starting on 127.0.1.1 url

### ISSUE THREAD

**Issue by fnnrodrigo** [paul-em/nogger#9]
Hi there!
I was trying to run nogger on my production website and it prints "Nogger listening on https://127.0.1.1:1337" and I cannot access it using the actual server IP. I guess it may be some detail I left behind. Could you please help me? =)

**Comment by paul-em** [comment]
Hi! 
I am working on a new version right now, that should be out soon. Hopefully this problem will then be resolved. 
For now check which webserver you are running and maybe proxy the request. For example in nginx you could do something like this


```
server {
        listen 443 ssl;
        server_name nogger.paulem.eu;

        index index.html index.htm;
        include /path/to/ssl.conf;

        location / {
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header Host $http_host;
                proxy_set_header X-NginX-Proxy true;
                proxy_pass http://127.0.0.1:1337;
                proxy_redirect off;
        }
}
```
